---
- name: Set up the repository gateway
  hosts: cvmfs_gw
  remote_user: root
  become: yes
  tags: gateway
  tasks:
    - name: Disable SELinux (it only causes pain)
      selinux: state=disabled

    - name: Start Firewalld
      service: name=firewalld enabled=yes state=started

    - name: Open firewall port tcp:80
      firewalld: service=http permanent=true state=enabled

    - name: Open firewall port tcp:4929
      firewalld: port=4929/tcp permanent=true state=enabled

    - name: Reload Firewalld
      service: name=firewalld enabled=yes state=reloaded

    - name: Install any prerequisites
      yum: name=httpd state=present

    - name: Start Apache
      service: name=httpd enabled=yes state=started

    - name: Install the CernVM-FS Yum repository
      yum:
        name: https://ecsft.cern.ch/dist/cvmfs/cvmfs-release/cvmfs-release-latest.noarch.rpm
        state: present

    - name: Install the CVMFS packages and dependencies
      yum: name="cvmfs,cvmfs-server,cvmfs-gateway"

    - name: Write S3 credential file
      template: src=s3.conf dest=/etc/cvmfs/{{ repo_name }}-s3.conf

    - name: Create the test repository
      command: cvmfs_server mkfs -o root -s /etc/cvmfs/{{ repo_name}}-s3.conf -w http://{{ s3_bucket_name }}.s3.cern.ch/cvmfs {{ repo_name }} creates=/etc/cvmfs/repositories.d/{{ repo_name }}

    - name: Add a gateway key to the repository
      copy: content="plain_text {{ gw_key_id}} {{ gw_key_secret }}\n" dest=/etc/cvmfs/keys/{{ repo_name }}.gw mode=400

    - name: Write /etc/cvmfs/gateway/repo.json
      template: src=repo.json dest=/etc/cvmfs/gateway/repo.json

    - name: Make local directory for the repository keys
      file: path=/tmp/keys state=directory

    - name: Download the keys of the newly created repo
      fetch: src="/etc/cvmfs/keys/{{ repo_name }}.{{ item }}" dest=/tmp/keys/ flat=yes
      with_items:
        - pub
        - crt
        - gw

    - name: Start the CVMFS repository services application
      service: name=cvmfs-gateway enabled=yes state=started

- name: Set up release managers
  hosts: cvmfs_rm
  remote_user: root
  become: yes
  tags: release_manager
  tasks:
    - name: Disable SELinux (it only causes pain)
      selinux: state=disabled

    - name: Install prerequisites
      yum: name="httpd"

    - name: Start Apache
      service: name=httpd enabled=yes state=started

    - name: Install the CernVM-FS Yum repository
      yum:
        name: https://ecsft.cern.ch/dist/cvmfs/cvmfs-release/cvmfs-release-latest.noarch.rpm
        state: present

    - name: Install the CVMFS packages and dependencies
      yum: name="cvmfs,cvmfs-server"

    - name: Copy test repository keys
      copy: src=/tmp/keys/ dest=/tmp/keys

    - name: Create CVMFS repository
      command: cvmfs_server mkfs -o root -w http://{{ s3_bucket_name }}.s3.cern.ch/cvmfs/{{ repo_name }} -u {{ rm_upstream }} -k /tmp/keys {{ repo_name }} creates=/etc/cvmfs/repositories.d/{{ repo_name }}
